---
# title: 
date: '`r format(Sys.time(), "%d %B, %Y")`'

bibliography: C:/Users/crosby/Documents/zotero-references.json
csl: common/journal-of-animal-ecology.csl
zotero: true

output: 
  word_document:
       reference_docx: common/word-styles-reference-jae.docx

fontsize: 12pt
mainfont: Cambria

fig_caption: yes


---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = normalizePath(".."))  #Sets the working directory to the project folder
```


# **Biodiversity Risk Assessment in the Oil Sands Region of Alberta, Canada** 
# Presentation notes 


### **Slide 1: Introduction** 
Hi again everyone. It's great to be able to do this presentation so early in the project cycle so we can start the feedback process and make sure we're all going down the same road in terms of understanding the project and what expectations are, and the potential, for developing this research. 

### **Slide 2:Roadmap** 
I want to start of with a quick roadmap of the presentation so we all know where we're going with this. 

- First, I'm going to set the context by describing how we are approaching this project, and why. I have to admit that I don't know my audience terribly well, so I'm likely going to be saying things you already know, but I want to make sure a frame this research correctly so that the subsequent parts make sense. 

- Second, I want to give a more specific description of what we mean by risk assessment, and talk about why we want to approach it this way. 

- Finally, I'm going to try to tie it together by talking about why this approach is so relevant to the decision-making process, because informing on-the-ground decisions is really the ultimate purpose of this research. 

### **Slide 3: Climate Change and Climate Adaptation** 
So, the big question facing us here is: how can we best understand and mitigate the risks to biodiversity imposed by oil sands development in Alberta. 
In the short term and at small spatial scales, we're mainly talking about habitat changes from disturbances like well pads, roads, and seismic lines. In the long term, however,and over large spatial extents, one of the bigger challenges in answering this question is dealing with the complications imposed by climate change.  

- Traditionally, we would have thought about mitigation, restoration, and biodiversity conservation according to historical responses of landscapes to disturbance, and within the context of the natural range of variability for species, ecosystems, and landscapes. 

- Because of climate change, however, we can say with a high degree of confidence that 'The world has moved on', meaning that things aren't happening the way they used to. 

- The wide-ranging and inevitable impacts of climate change on disturbance regimes, vegetation successional pathways, and species survival and reproduction means that reliance on traditional paradigms in wildlife management and restoration ecology are unlikely to achieve long term, large scale conservation goals. 

- And so of course, many species and ecosystems are vulnerable to the effects of climate change

- As a result, managers are increasingly shifting to a climate adaptation approach to managing wildlife and developing long-term conservation plans in the face of climate change. 


### **Slide 4: Some terms** 
As we talk about the context, I want to give specific definitions for these terms: 

- First is Vulnerability, which is usually defined as the combination of exposure, sensitivity, and adaptive capacity to new conditions brought on by climate change. 

  - For example, the boreal forest is warming at a much faster rate than other areas of the globe, meaning that boreal species generally have a higher exposure to climate change than many others. Within the boreal, there are also areas and ecosystems that can have more exposure, such as grasslands, and also refugia where changes will be less drastic. 
  
   - Sensitivity is the degree to which a species is affected by climate change. It has been shown that warmer and drier conditions have a big effect on seedling survival and tree growth in a number of boreal conifers, meaning they can be highly sensitive when exposed. Another example of sensitivity is moose being negatively affected by the increase in winter tick populations brought on by warmer winters. 
   
   - Finally adaptive capacity is the ability of a species to cope with or adjust to the effects of climate change, such as species being able to shift their range or respond behaviourally. For example, we have seen a number of species expanding their ranges northward as temperatures warm, where previously they would have been limited by extreme winter temperatures. Other species, such as the Karner Blue Butterfly, have had their reproduction negatively affected by longer growing seasons, and with their limited dispersal ability, have been unable to colonize new habitats where the climate is more conducive. 
   
   
- But the fact is, these same aspects of species that define climate vulnerability are equally applicable to effects of industrial development. Some species will be affected very little -- or even respond positively --  such as some generalist bird species that do well around human development; while others, such as caribou, will have a strong negative response due to high exposure and sensitivity and a lack of adaptive capacity. 

- Second when we say adaptation in this context, we are talking about the intentional adjustment of natural systems to reduce risks from climate change. 

  - This is a big topic, but coming back to the Karner Blue Butterfly, an example of adaptation would be using assisted migration to help them colonize new areas to avoid negative impacts of climate change. In the case of caribou, which are subject to increased predation in areas with extensive linear features, an adaptation approach would be the wolf culling.  
  
- So, essentially, adaptation is the result of the fact that we know we can't go back to previous conditions, so we need to set new expectations and find new strategies to conserve biodiversity under changing conditions. 
  
- One thing that is potentially problematic in the OSR is that being in an area with high levels of anthropogenic disturbance can actually increase species vulnerability to climate change stressors. 


### **Slide 5: Ecosystem transformation** 
One of the biggest challenges in the OSR is the potential for ecosystem transformations brought on by the interaction of climate change and industrial development. 

Historically, ecosystems changed as a result of natural fluctuations in climate and other processes. Human expansion and the development of agriculture added another dimension to these changes. Now, we are seeing the synergistic effects of industrialization and anthropogenic disturbance accelerate the rate of change and create increased uncertainty in future conditions. 

In terms of forests, what we see is that globally, forests are becoming younger and more open, and climatic extremes are favoring trees of lower stature. 

- Forest tree species composition is trending towards species more tolerant of warmer temperatures drier conditions. 

### **Slide 6: Changing response pathways**  
Now, it is possible for climate change to cause a complete regime shift from forest to non-forest, and shifts like this on a large scale have been predicted for large parts of boreal Alberta, converting it to more of a Parkland ecosystem like we have around Edmonton. 

However, in the nearer-term, it is much more likely that we will see response pathways to disturbance that resemble those described by Seidle and Turner, where the forest remains but changes either structurally or compositionally or both. 

Essentially, they described 5 different possible outcomes: 

1. On the one hand, after a disturbance, a forest could come back essentially the way it was before, what they called Resilience, where the forest follows the historic successional pathway. 

2. On the other hand, a forest could undergo restructuring, where it regrows with the same species composition but a different structure, for example trees could be smaller or less dense; or Reassembly, where the structure is the same but the species are different. 

3. If a forest changes in both composition and structure, they termed that 'Replacement', becasue it is essentially a whole different forest type. 

4. Most drastically, an area could undergo a total 'Regime Shift', where it is no longer even a forest. 

Why is this important? Because if we are going to estimate the risks to species from oil sands development, we have to do so within the context of the primary disturbances and successional pathways within the region. In this case, the major disturbances in the region are fire and forest harvesting, meaning any mitigation strategies must take into account how forests respond to those disturbances under climate change. And one thing we've seen is that high levels of anthropogenic disturbance, such as forest harvesting, can accelerate changes in forest response pathways beyond what climate change alone would do. 

### **Slide 7: Effects of Forest Fragmentation** 
When talking about *in situ* oils sands development, however, the issue isn't large-scale disturbances but rather high levels of fragmentation brought on by mining infrastructure, such as well pads, pipelines, roads and, most extensively, seismic lines. While these developments result in direct habitat loss, the extensive network of exploratory seismic lines fragment landscape patterns and alter movements of organisms, substantially affecting landscape patterns, ecological processes, and biotic interactions among species. 

I know we're all well aware of how linear features negatively affect caribou through apparent competition and increased predation, and we're beginning to understand more about how fragmentation affects species that rely on forest interior habitat, such as many songbirds. 

Although the intensity of oil sands disturbance from *in situ* mining is lower locally than surface mining, the broad extent of the area affected and their potential to degrade adjacent interior habitat, as well as alter animal movements, means the impact to biodiversity could be greater. 

### **Slide 8: The overall goals of the Risk Assessment framework** 

- There has already been a great deal of work done to examine how forests and peatlands in the OSR recover from oil sands disturbances, as well as on how these disturbances affect wildlife species such as songbirds, caribou, wolves, etc.. 

- However, with the rapid rate of climate change, it is very likely that many species and ecosystems will not respond as historically, and these shifts may exceed the adaptive capacity of many organisms, leading to unanticipated outcomes from management and mitigation decisions.  

- As such, the goal of this research is to develop a framework for assessing species vulnerabilities that takes into account both industrial development and climate change, and use that assessment to inform the development of adaptation strategies. 

- The key aspect of this framework is that it will have to deal with the many uncertainties in what the future holds, as well as all of the things we don't or can't know. 

- So if there is one word I want you to keep in mind as we go through this proposed research, it is UNCERTAINTY. 

- This uncertainty is why, instead of going down the traditional pathway of prediction, we are proposing a true risk assessment approach to understanding and mitigating these vulnerabilities. 


### **Slide 9: The problem of predicting the future** 
I want to take a minute here to define the problem in using models to predict future ecological conditions and species populations, and why we think it's important to take a risk assessment approach. 

There are 2 main things to keep in mind here: 

1. We know that the future is uncertain 

2. Working within our knowledge limitations, it is very difficult (some might say impossible) to accurately predict future ecosystem states across large spatial extents and over long time horizons 


### **Slide 10: The limits of deterministic modeling** 
At this time, the most widely used method to predict species responses to changing environments is to model how something like percent forest cover and other variables will change over time, using drivers such as wildfire, timber harvest, and forest growth, and then use a previously fitted habitat model to predict species population at a future time based on the mean expected value of future forest cover. This is an example of what we call a deterministic model, where the mean or 'expected' value is used as the response as determined by the predictor variables. 

In this example plot, the blue dots represent a 'realized' value of landscape-scale forest cover at 10 year intervals from 10 separate runs of a simulation model, and the blue line is the 'expected' value that would be used in deterministic prediction framework. 

This as simplified example, but it does show essentially how the process is most often used.  

### **Slide 11: The limits of deterministic modeling** 
The problem is that there is a great deal of variability in the potential outcomes of the many processes driving future forest cover across the landscape, including wildfire and timber harvesting. This means that there are a wide range of potential outcomes in terms of future conditions, creating a lot of uncertainty in what will actually happen. 

And that uncertainty tends to get greater as the time since the origin increases.  

I like to use the example of trying to predict the day a baby will be born. When they model the birth date as a function of time since conception, they get an expected value of 39 week, and using that they predict a 'due date.' How many babies are actually born on their due date? I have 2 kids: one was born a week earlier and the other one 2 weeks after. 

So the point I'm trying to make is that relying on that mean predicted value of future conditions, as is typically done within a deterministic framework, might not be the best option for making management and conservation decisions. 

### **Slide 12: Forecasting and the risk assessment framework** 
What we're proposing, instead, to use ecological forecasting within a risk assessment framework to inform the decision-making process.  

Forecasting itself is a way of estimating future conditions based on our knowledge and assumptions about the ecological processes driving those conditions. It is typically done using simulation models that incorporate those processes. 

Risk assessment is a way of formally accounting for uncertainties in the outcomes of those processes. The assessment is typically carried out by running many iterations of a simulation model and calculating the probability of getting specific outcomes. 

### **Slide 13: Implementing the risk assessment approach** 
I want to illustrate what I've been describing using a paper that I think really lays the groundwork for why we should be taking a risk assessment approach, and provides an initial roadmap for getting started on this research. 

- This is a paper in Forest Ecology and Management lead by Colin Daniel at ApexRMS consulting service, where they show how failing to consider uncertainty in the outcomes of ecological processes -- in this case wildfire and timber harvest -- means that timber harvest projections are almost always going to be overly optimistic; particularly under future climate change. 

They issue they illustrate in the paper is that in planning forest management over long time scales, most planners set target harvest rates for each time period from deterministic projections based on mean expected values of models for wildfire and timber harvest, ignoring the high variability in these processes over time, as well as the potential for climate change to increase wildfire through time. Kind of like betting that all your kids and grandkids will be born on their due date.  

They then developed a state and transition simulation model that could both replicate the deterministic projections from the forest planning software, and also incorporate variability in the processes, including climate change, to provide a more comprehensive picture of the range of possible harvest levels. Essentially, they created a stress test for the forest management plan. 


### **Slide 14: Failure to consider uncertainty in wildfire and harvest**

Without going into a lot of detail on the methods, what they are showing here in the plot on the left is that year-to-year uncertainty in wildfire was high, particularly under the climate change scenario, where the predicted proportion of the landscape burned is likely to be much higher than expected from the deterministic models. 

The plot on the right shows the volume of timber harvest each decade on the y axis, illustrating that again, uncertainty in timber harvest volumes can be high, and shortfalls in annual timber harvest are likely to occur regularly. These shortfalls were not evident from the deterministic model predictions. They also show that these shorfalls are likely to increase substantially over time as a result of climate change. 

### **Slide __: Probabilities of harvest shortfall**
What this plot is showing is a density distribution of the probability of maximum decadal harvest shortfalls over a 100 year period. 
What it shows is a mean maximum shortfall of ~23% under the no climate change scenario, and a mean maximum shortfall of ~61% under climate change. 

Here, I want to make the point that what they were interested in in this study was the risk of falling below expected timber harvest volumes, but based on this framework, we could easily be looking at shortfalls in expected amounts wildlife habitat or key demographic rates such as reproduction or dispersal ability. 



### **Slide__: Challange of separating forestry from oil sands** 
Talk about how we can use existing landscape simulation models as baselines, and then build oil sands development and fragmentation into it. 

Now, I don't want you to think from this that we're focusing a lot on forestry here, because we aren't. 
In fact, the idea is to use existing landscape simulation models as baseline models, and then build in Oil Sands Footprint and Fragmentation effects on top of that. 




### **Slide __: setting management reference points** 

- need to define what we mean by 'sustainable' 

- Rather than a traditional population model, we have a SDM that assumes a relationship between habitat and population 

- Rather than a harvest dynamics model, we have a model of population response to disturbance that links to the habitat-population model 

- Rather than being limited by population assessment, we are limited by our understanding of 

- We will use simulations and sensitivity analysis to identify uncertainties that have a large effect on performance measures 


### **Slide __: adapting research to the decision-making context** 

- Making state-dependent management decisions 

- Decide on appropriate performance measures

- making sure that guidance for climate adaptation is constant with the decision space and authority of the decision-makers, as well as the spatial scales at which the changes are occurring over which the managers are operating. 


### **Slide __: The critical importance of spatial scale** 


### **Slide __: Final Thought** 

We can't really make predictions because we can't model the system perfectly, and there are too many things we don't know. There's just too much uncertainty. 

However, we shouldn't let that stop us from making the best decisions we can based on what we do know or can shrewdly guess. 

On the other hand, we shouldn't pretend we know things we don't, and make decision based on predictions we know a priori are almost certain to be wrong.  

The answer is to explicitly incorporate that uncertainty into the decision-making process, and by that use our best estimates of the risks of various outcomes to guide us through the process. 




